algoritmo "Soma_Parametros_referencia"
var
   X, Y: INTEIRO
procedimento soma (var A, B: inteiro)
inicio
      a <- a + 1
      b <- b + 2
      escreval ("Valor de A = ", A)
      escreval ("Valor de B = ", B)
      Escreval ("Soma A + B = ", A+B)
fimprocedimento
inicio
      X <- 4
      Y <- 8
      soma (X, Y)
      Escreval ("Valor de X = ", X)
      Escreval ("Valor de Y = ", Y)
fimalgoritmo
